### ISSUE TITLE
64-bit issue

### ISSUE THREAD

**Issue by twustep** [tapstream/tapstream-sdk#45]
Hello, 

After upgrading to the 64-bit version for Titanium, there is an issue when firing custom events:

example: 
tapstream.fireEvent('ts-registration-event', false, {
			    'ts-track-userId': data.results.user.id,
			});

I am pretty sure it is an issue with the tapstream sdk. When I roll back to non-64-bit it works fine.

Thanks!

**Comment by adambard** [comment]
Thanks for your report! We didn't see this issue in our testing, do you think you could provide the accompanying error message so that we can track that down for you?

**Comment by twustep** [comment]
Sure, to be more specific while debugging in titanium, the app in the iPhone Simulator crashes when the event triggers. iPhone Simulator keeps running but it kicks you to the homepage of the iPhone.

Unfortunately, the log flashes before catching information, however I will track down the actual log file and see what I can find.

**Comment by twustep** [comment]
I just recorded the output debug screen so I could catch the error. 

Unfortunately, when the error happens, no specific information is shown on the output screen, all it does is show output as if it where restarting/recompiling the app. 

So not much useful info in the logs. 

![screen shot 2015-03-20 at 11 25 06 am](https://cloud.githubusercontent.com/assets/3392322/6754568/cf9ce9b0-cef3-11e4-916b-d045942c2734.png)

**Comment by twustep** [comment]
And this is what happens on the iOS Simulator debug. 

![screen shot 2015-03-20 at 11 44 26 am](https://cloud.githubusercontent.com/assets/3392322/6754990/8eea0d6e-cef6-11e4-8f3c-688b8da6293d.png)

**Comment by adambard** [comment]
Fixed in 28563ef7081509c6666c0b7781d0e1d6c51d7d4f. Thanks so much for your report and debugging info!

**Comment by twustep** [comment]
Thanks Adam, 

Not sure how you figured out what it was from my general logs, but that was pretty awesome. We have tested on our side and all seems to be working. Thanks again!
