### ISSUE TITLE
Update the version of Tapstream SDK to 2.8.9 in pod

### ISSUE THREAD

**Issue by luohui8891** [tapstream/tapstream-sdk#54]
Update the version of Tapstream SDK to 2.8.9 in pod.
I have to use `pod 'Tapstream', :git => 'https://github.com/tapstream/tapstream-sdk.git', :tag => 'v2.8.9-objc'` for now.

**Comment by adambard** [comment]
Whoops, missed that one. Thanks for the PR!

**Comment by adambard** [comment]
Oh it's not a PR :). Well thanks for the heads-up, I'll fix that now.

**Comment by nsitarz** [comment]
2.8.9 is now published to trunk.

**Comment by luohui8891** [comment]
Thank you.
