### ISSUE TITLE
WoM crashed on iPad

### ISSUE THREAD

**Issue by voidmorn** [tapstream/tapstream-sdk#62]
After I click "accept" on WoM offer,  the app crashed and show message:

`Uncaught exception: UIPopoverPresentationController (<_UIAlertControllerActionSheetRegularPresentationController: 0x7f85215ba3e0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.
`

ShowOffer code in my app :
`if(offer) {
            [wom showOffer:offer parentViewController:self.tabBarController];
        }
`

I tried to find the reason in SDK  and located codes:
`UIViewController *parent = self.offerViewController.parentViewController;    
UIActivityViewController* c = [[UIActivityViewController alloc]
                                       initWithActivityItems:@[offer.message] applicationActivities:nil];
`

Maybe we should set the UIActivityViewController.popoverPresentationController.sourceView or barButtonItem for iPad ?

I added test code `c.popoverPresentationController.sourceView = parent.view;`  in SDK and it seemed to work.
But the share view's position is not good.

![image](https://cloud.githubusercontent.com/assets/3390634/9871936/7370311c-5bc8-11e5-9ba5-d22ed717dee7.png)

**Comment by adambard** [comment]
Thanks for the report! While I roll out the fix, here's a quick patch:

In `dismissedOffer`, instead of changing the sourceView property of the popover controller, a new UIPopoverController is created to present the share view. Replace `[parent presentViewController:c animated:YES completion:nil];` in dismissedOffer (line 350 or so) with:

```
		if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone) {
			[parent presentViewController:c animated:YES completion:nil];
		}else{
			UIPopoverController *popup = [[UIPopoverController alloc] initWithContentViewController:c];
			[popup presentPopoverFromRect:CGRectMake(parent.view.frame.size.width/2, parent.view.frame.size.height, 0, 0)
								   inView:parent.view
				 permittedArrowDirections:UIPopoverArrowDirectionUnknown
								 animated:YES];
		}
```

The popup will appear at the bottom center, which testing has determined looks just about as silly as anywhere else.

**Comment by voidmorn** [comment]
@adambard New version works, thanks!

**Comment by voidmorn** [comment]
@adambard 
On iOS 7 iPad, it show 
`WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[UIPopoverController _commonPresentPopoverFromRect:inView:permittedArrowDirections:animated:]: Popovers cannot be presented with UIPopoverArrowDirectionUnknown.
`

**Comment by adambard** [comment]
Thanks for the report, sorry about that.

I don't have an iOS 7 device/simulator handy, but upon further research, I think your original solution was the best one. I'll be rolling out a new release tomorrow with the following presentation code:

```
		c.popoverPresentationController.sourceRect = CGRectMake(parent.view.frame.size.width/2, parent.view.frame.size.height, 0, 0);
		c.popoverPresentationController.sourceView = parent.view;
		[parent presentViewController:c animated:YES completion:nil];
```

If you could check t

**Comment by voidmorn** [comment]
@adambard 
Replaced the code on iOS 7 iPad:
`WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[UIActivityViewController popoverPresentationController]: unrecognized selector sent to instance 0x18405320
`

I am going to  discard this function on iOS 7 iPad. And I think that supporting 8 & 9 is enough.

iOS 7 always makes me cry...

Thanks for your patience.

**Comment by adambard** [comment]
I see, because popoverPresentationController won't exist prior to iOS 8. That's useful, thanks for the extra info -- I should be able to build out both iOS <= 7 and >= 8 support this way.
