### ISSUE TITLE
2.9.6 introduced use of dispatch_get_current_queue which is deprecated since 6.0

### ISSUE THREAD

**Issue by ileitch** [tapstream/tapstream-sdk#65]
https://github.com/tapstream/tapstream-sdk/blob/8a52caa5c8c47f56d88c3d3d98e922b75502a2a2/objc/Core/TSCore.m#L386

`dispatch_get_current_queue` has been deprecated since iOS 6.0. Perhaps you should consider configuring your CI environment to fail the build when compiler warnings are detected (I noticed because our own app build failed for this very reason).

I didn't spend too much time reading the code, but `TSCore` should probably be using an internal queue, rather than global queues (both default and high priorities are used).

**Comment by adambard** [comment]
Sorry for the trouble! We're presently migrating towards an internal queue for this and other reasons, expect that pretty soon.

**Comment by adambard** [comment]
Fixed in latest release.
